name: build-on-push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: build debug
        run:  msbuild msvc2022\oblast.sln -t:rebuild -verbosity:quiet -property:Configuration=Debug
      - name: build release
        run:  msbuild msvc2022\oblast.sln -t:rebuild -verbosity:quiet -property:Configuration=Release
      - name: upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: oblast.release.zip
          path: |
            bin\Release\blast.exe
            bin\Release\add.exe
          retention-days: 14
      - name: upload debug artifact
        uses: actions/upload-artifact@v3
        with:
          name: oblast.debug.zip
          path: |
            bin\Debug\blast.exe
            bin\Debug\add.exe
          retention-days: 14
