name: Generate Profiling Graphs


on:
  push:
    branches:
      - main

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Gnuplot
        run: sudo apt-get update -y

      - name: Install Gnuplot
        run: sudo apt-get install gnuplot -y --fix-missing

#       alt: ?set datafile separator "5#5char6#6" means "," instead of tab/whitespace?
      - name: Generate Graph for Intel GPU
        run: |
            gnuplot -e "set term svg; \
                      set datafile separator ','; \
                      set key fixed left top vertical Right noreverse enhanced autotitle box lt black linewidth 1.000 dashtype solid \
                      set key autotitle columnhead; \
                      set title 'Intel GPU profile'; \
                      set xlabel 'Nx1000'; \
                      set ylabel 'Time(ms)'; \
                      set output 'intel.svg'; \
                      plot 'profile/nvidia.csv' u 1:2 w lines, '' u 1:3 w lines"

      - name: Generate Graph for NVIDIA GPU
        run: |
            gnuplot -e "set term svg; \
                      set datafile separator ','; \
                      set key autotitle column; \
                      set title 'Intel GPU profile'; \
                      set xlabel 'Nx1000'; \
                      set ylabel 'Time(ms)'; \
                      set output 'nvidia.svg'; \
                      plot 'profile/nvidia.csv' u 1:2 w lines title 'AVX', '' u 1:3 w lines title 'GPU'"

      - name: Store Intel Graph in Repository
        uses: actions/upload-artifact@v3
        with:
          name: intel.svg
          path: intel.svg

      - name: Store Graph in Repository
        uses: actions/upload-artifact@v3
        with:
          name: nvidia.svg
          path: nvidia.svg

# refrences:
# "u 1:2" is shorthand for "using 1:2"
# "w lines" is shorthand for "with lines"
# https://gnuplot.sourceforge.net/demo/layout.html
# https://gnuplot.sourceforge.net/demo/
# https://stackoverflow.com/questions/51687096/gnuplot-autotitle-coloumnhead-key-and-datafile-with
# https://raymii.org/s/tutorials/GNUplot_tips_for_nice_looking_charts_from_a_CSV_file.html
# https://stackoverflow.com/questions/12818797/how-to-plot-several-datasets-with-titles-from-one-file-in-gnuplot
