name: Generate Performance Graphs

on:
  push:
    branches:
      - main

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Gnuplot
        run: sudo apt-get update -y

      - name: Install Gnuplot
        run: sudo apt-get install gnuplot -y --fix-missing

      - name: Generate Graph for Intel GPU
        run: |
            gnuplot -e "set term svg; \
                      set output 'intel.svg'; \
                      set title 'Intel GPU profile'; \
                      set xlabel 'Nx1000'; \
                      set ylabel 'Time'; \
                      set key autotitle columnheader; \
                      plot 'profile/intel.csv' \
                      using 1:2 with lines title 'AVX' \
                      using 1:2 with lines title 'GPU'"

      - name: Generate Graph for NVIDIA GPU
        run: |
            gnuplot -e "set term svg; \
                      set output 'nvidia.svg'; \
                      set title 'NVIDIA GPU Profile'; \
                      set key autotitle columnheader; \
                      plot 'profile/nvidia.csv' using 1:3 with lines"

      - name: Store Intel Graph in Repository
        uses: actions/upload-artifact@v2
        with:
          name: intel.svg
          path: intel.svg

      - name: Store Graph in Repository
        uses: actions/upload-artifact@v3
        with:
          name: nvidia.svg
          path: nvidia.svg
