name: release
on:
  release:
    types: [published]
jobs:
  my-job:
    runs-on: windows-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: build release
        run: msbuild msvc22\oblast.sln -t:rebuild -verbosity:quiet -property:Configuration=Release

      - name: upload sts.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: bin\Release\sts.exe
          asset_name: sts.exe
          asset_content_type: application/exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: upload oblast.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: bin\Release\oblast.exe
          asset_name: oblast.exe
          asset_content_type: application/exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload system.tools.exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: bin\Release\system.tools.exe
          asset_name: system.tools.exe
          asset_content_type: application/exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
